---
id: Stream_Filter
name: Stream_Filter
full: PHP stream filters library
description: A library of various stream filters.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Stream_Filter
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
  optional:
    composer:
      horde/test: ^3
